Module2 task1
htmlacademy-react/2408243-six-cities-14 pull request #2
Opened 2023-10-19 17:44 UTC by dtyunegov

2023-10-19 17:47 UTC, romien94 commented on src/components/Favorites/FavoritesCard.tsx
> +        <span>{ card?.mark}</span>
отформатируй файлик

2023-10-19 17:48 UTC, romien94 commented on src/components/Favorites/FavoritesCard.tsx
> +import CardProps from '../../props/FavoriteCardProps';
пропсы для реакт компонентов обычно хранятся в том же файлике, что и сам компонент. Если ты используешь тим Card, то логичнее закинуть его в types/Card.ts

2023-10-19 17:49 UTC, romien94 commented on src/components/Favorites/FavoritesCard.tsx
> +const FavoritesCard = ({ card }: Card) => (
а вот здесь должен быть FavoritesCardProps

2023-10-19 17:49 UTC, romien94 commented on src/components/Favorites/FavoritesPlace.tsx
> +import FavoritePlaceProps from '../../props/FavoritePlace';
то же самое, что и выше с пропсами

2023-10-19 17:50 UTC, romien94 commented on src/components/Favorites/FavoritesPlace.tsx
> +  place: FavoritePlaceProps;
аналогично выше указанному

2023-10-19 17:51 UTC, romien94 commented on src/components/common/Footer/index.tsx
> +    <footer className="footer container">
контейнер лучше сделать отдельным компонентом

2023-10-19 17:52 UTC, romien94 commented on src/components/common/Header/index.tsx
> +      <div className="container">
можно вынести в отдельный компонент для переиспользования

2023-10-19 17:53 UTC, romien94 commented on src/props/FavoriteCardProps.ts
> +type CardProps = {
лучше назвать CardItem, т.к. пропсы всё-таки намекают на реакт-компоненты

2023-10-19 17:54 UTC, romien94 commented on src/pages/main/index.tsx
> +                <CitiesCard />
сверху ты уже используешь маппинг. почему бы здесь то же не сделать?

2023-10-19 17:54 UTC, romien94 commented on src/pages/Offer/index.tsx
> +                    defaultValue={''}
строки можно передавать без {}

2023-10-19 17:55 UTC, romien94 commented on src/pages/Offer/index.tsx
> +              <div className="offer__image-wrapper">
тоже можно сделать через map, чтобы не было копипасты

2023-10-19 17:56 UTC, romien94 commented on src/pages/Favorites/index.tsx
> +    <Header></Header>
если внутрь в качестве children не передаёшь ничего, можно использовать просто <Header />

2023-10-19 17:57 UTC, romien94 commented on src/pages/Favorites/index.tsx
> +import Footer from '../../components/common/Footer';
слишком длинный путь получается. 
можно, во-первых, сократить ../../ до components/common/Footer
во-вторых, можно реэкспортировать файлики из components из index.ts

2023-10-19 17:58 UTC, dtyunegov commented on src/components/Favorites/FavoritesCard.tsx
> +const FavoritesCard = ({ card }: Card) => (
мм.. карточка номера используется на 3-х страницах - Favorites, Offer и Main с одинаковыми данными, только с отличием в верстке. Если делать  FavoritesCard, OfferCard и MainCard, то получится дублирование кода

2023-10-19 17:59 UTC, romien94 requested changes
накидал немного комментариев, как можно улучшить код :)

2023-10-19 18:00 UTC, dtyunegov commented on src/components/Favorites/FavoritesCard.tsx
> +const FavoritesCard = ({ card }: Card) => (
дошло, понял

2023-10-19 18:14 UTC, dtyunegov commented on src/components/Favorites/FavoritesCard.tsx
> +import CardProps from '../../props/FavoriteCardProps';
исправлено

2023-10-19 18:14 UTC, dtyunegov commented on src/components/Favorites/FavoritesCard.tsx
> +const FavoritesCard = ({ card }: Card) => (
исправлено

2023-10-19 18:14 UTC, dtyunegov commented on src/components/Favorites/FavoritesPlace.tsx
> +import FavoritePlaceProps from '../../props/FavoritePlace';
исправлено

2023-10-19 18:15 UTC, dtyunegov commented on src/components/Favorites/FavoritesPlace.tsx
> +  place: FavoritePlaceProps;
исправлено

2023-10-19 19:56 UTC, dtyunegov commented on src/components/common/Footer/index.tsx
> +    <footer className="footer container">
зачем? Каким образом? Класс контейнер относится к тегу футер, если тег футер вынести в отдельную сущность, то содержимое будет так же передаваться в контейнер, по итогу в этом компоненте будет такое количество кода, но при этом добавится сущность.
Если весь футер вынести в отдельную сущность, то весь этот код будет в ней, и просто увеличится вложенность.
В данном случае вижу возможность вынести в компонент a>img. И назвать LinkImage или ImageWithLink и по всему проекту его использовать

2023-10-19 20:03 UTC, dtyunegov commented on src/props/FavoriteCardProps.ts
> +type CardProps = {
изменено types>Card

2023-10-19 20:04 UTC, dtyunegov commented on src/pages/Offer/index.tsx
> +                    defaultValue={''}
исправлено

2023-10-20 12:31 UTC, dtyunegov commented on src/pages/main/index.tsx
> +                <CitiesCard />
сделано

2023-10-20 12:31 UTC, dtyunegov commented on src/pages/Favorites/index.tsx
> +    <Header></Header>
исправлено

2023-10-20 20:16 UTC, dtyunegov commented on src/components/Favorites/FavoritesCard.tsx
> +        <span>{ card?.mark}</span>
исправлено

2023-10-20 20:16 UTC, dtyunegov commented on src/pages/Offer/index.tsx
> +              <div className="offer__image-wrapper">
сделано

2023-10-20 20:19 UTC, dtyunegov commented on src/pages/Favorites/index.tsx
> +import Footer from '../../components/common/Footer';
сделан реэкспорт.

2023-10-22 16:21 UTC, romien94 approved these changes

2023-10-22 16:22 UTC, merged

2023-10-24 20:21 UTC, dtyunegov commented on src/components/common/Header/index.tsx
> +      <div className="container">
исправлено