Module4 task1
htmlacademy-react/2408243-six-cities-14 pull request #6
Opened 2023-11-08 10:13 UTC by dtyunegov

2023-11-09 08:12 UTC, romien94 commented on src/components/favorites/FavoriteList/FavoriteList.tsx
> +              .filter((offer) => offer.city.name === city)
достаточно будет одного .map, где ты будешь прописывать такое условие:
offer.city.name === city ? <FavoritesCard offer={offer} key={offer.id} /> :  null

2023-11-09 08:13 UTC, romien94 commented on src/components/offer/ReviewForm/ReviewForm.tsx
> +        onChange={(evt) => {
для читаемости лучше вынести в функцию наверх, а тут передать её по ссылке в onChange

2023-11-09 08:15 UTC, romien94 commented on src/pages/Favorites/Favorites.tsx
> +  function getFavoritesOffers(): OfferType[] {
Эм. Кажется, лучше константу favoritesOffers сделать, куда передавать уже отфильтрованные значения

2023-11-09 08:17 UTC, romien94 requested changes
в целом, всё окей, но нужно кое-что поправить

2023-11-13 11:15 UTC, dtyunegov commented on src/components/favorites/FavoriteList/FavoriteList.tsx
> +              .filter((offer) => offer.city.name === city)
исправлено

2023-11-13 11:15 UTC, dtyunegov commented on src/components/offer/ReviewForm/ReviewForm.tsx
> +        onChange={(evt) => {
исправлено

2023-11-13 11:15 UTC, dtyunegov commented on src/pages/Favorites/Favorites.tsx
> +  function getFavoritesOffers(): OfferType[] {
исправлено

2023-11-13 11:19 UTC, merged